// Generated by CoffeeScript 1.4.0
var album, get_albums, get_feed, get_photo, get_photos, height, photo, user, width, _ref;

get_feed = function(query, params, callback) {
  var api_url;
  if (params == null) {
    params = {};
  }
  params['alt'] = 'json';
  params['v'] = '4';
  params['max-results'] = 10000;
  api_url = "https://picasaweb.google.com/data/feed/api/" + query;
  return $.getJSON(api_url, params, function(data, textStatus, jqXHR) {
    console.dir({
      api_url: api_url,
      params: params,
      data: data,
      textStatus: textStatus,
      jqXHR: jqXHR
    });
    return callback(data);
  });
};

get_albums = function(user) {
  return get_feed("user/" + user, {
    kind: 'album'
  }, function(data) {});
};

get_photos = function(user, album) {
  return get_feed("user/" + user + "/albumid/" + album, {
    kind: 'photo'
  }, function(data) {});
};

get_photo = function(photo) {
  return get_feed("user/" + user + "/albumid/" + album + "/photoid/" + photo, {
    'full-exif': 'true'
  }, function(data) {});
};

_ref = window.location.hash.replace('#', '').split('/'), user = _ref[0], album = _ref[1], photo = _ref[2], width = _ref[3], height = _ref[4];

if (width == null) {
  width = 640;
}

if (height == null) {
  height = 480;
}

console.dir({
  user: user,
  album: album,
  photo: photo,
  width: width,
  height: height
});

get_albums(user);

get_photos(user, album);

get_photo(user, album, photo);
