// Generated by CoffeeScript 1.4.0
var loadJSON;

window.index = [];

loadJSON = function(callback) {
  return $.ajax({
    url: 'articles/index.json',
    dataType: 'json',
    error: function() {
      return console.dir(arguments);
    },
    success: function(data) {
      return callback(data);
    }
  });
};

$(function() {
  return loadJSON(function(data) {
    return window.index = data.articles;
  });
});
